/**
 * Extreme Points (EP) set.
 *
 * A C-EP is a "corner" in 3D space, typically generated by the
 * placement of a box. The set starts with the origin (0, 0, 0) —
 * the back-left-floor corner — and grows as boxes are placed.
 *
 * For axis-aligned boxes with 6 sides, placing a box can produce
 * at most 3 new EPs (one per positive axis). We also project
 * those EPs to the container interior, dedupe, and prune any
 * EPs that fall inside a just-placed box.
 *
 * Gravity constraint: we never generate a downward (-Y) EP.
 */

import type { AABB, Bounds, Size3, Vec3 } from "./geometry";
import { aabbFromMin } from "./geometry";

export type ExtremePoint = Vec3;

export interface ExtremePointSet {
  points: ExtremePoint[];
}

/** Build the initial EP set — single origin at the floor corner. */
export function createEPSet(): ExtremePointSet {
  return { points: [{ x: 0, y: 0, z: 0 }] };
}

// Re-export Bounds so callers can import from this file.
export type { Bounds };

/** Project an EP to the container interior: clamp its position so
 *  the candidate box (of given size) placed at the EP still fits.
 *  If the box cannot fit, returns null. */
export function projectEP(
  ep: ExtremePoint,
  size: Size3,
  bounds: Bounds
): ExtremePoint | null {
  if (
    ep.x < 0 ||
    ep.y < 0 ||
    ep.z < 0 ||
    ep.x + size.l > bounds.l ||
    ep.y + size.h > bounds.h ||
    ep.z + size.w > bounds.w
  ) {
    return null;
  }
  return { x: ep.x, y: ep.y, z: ep.z };
}

/** Add a new EP to the set; returns true if the EP was new. */
function tryAdd(set: ExtremePointSet, ep: ExtremePoint): boolean {
  for (const p of set.points) {
    if (p.x === ep.x && p.y === ep.y && p.z === ep.z) return false;
  }
  set.points.push(ep);
  return true;
}

/**
 * After a box of `size` is placed with min corner `placed`, generate
 * the up-to-3 new EPs:
 *   - +X: (placed.x + size.l, placed.y, placed.z)
 *   - +Y: (placed.x, placed.y + size.h, placed.z)
 *   - +Z: (placed.x, placed.y, placed.z + size.w)
 *
 * Also prune any existing EPs that fall inside the new box, and
 * project the new EPs to the container bounds.
 */
export function addAfterPlacement(
  set: ExtremePointSet,
  placed: Vec3,
  size: Size3,
  bounds: Bounds
): void {
  // 1) Prune EPs inside the new box.
  const box = aabbFromMin(placed, size);
  set.points = set.points.filter((p) => !pointInsideAABB(p, box));

  // 2) New EPs.
  const candidates: ExtremePoint[] = [
    { x: placed.x + size.l, y: placed.y, z: placed.z },
    { x: placed.x, y: placed.y + size.h, z: placed.z },
    { x: placed.x, y: placed.y, z: placed.z + size.w },
  ];
  for (const c of candidates) {
    // Project to bounds (drop if out).
    if (
      c.x < 0 ||
      c.y < 0 ||
      c.z < 0 ||
      c.x > bounds.l ||
      c.y > bounds.h ||
      c.z > bounds.w
    ) {
      continue;
    }
    if (pointInsideAABB(c, box)) continue;
    tryAdd(set, c);
  }
}

/** Test if a point is strictly inside an AABB. */
function pointInsideAABB(p: Vec3, box: AABB): boolean {
  return (
    p.x > box.min.x &&
    p.x < box.max.x &&
    p.y > box.min.y &&
    p.y < box.max.y &&
    p.z > box.min.z &&
    p.z < box.max.z
  );
}

/**
 * Remove an EPs that fall inside a removed box. Used when
 * simulated annealing reverts a placement.
 */
export function removeInsideAABB(
  set: ExtremePointSet,
  box: AABB
): void {
  set.points = set.points.filter((p) => !pointInsideAABB(p, box));
}
